insert into shops (name, address, owner, email) values ('Personal Care Products, LLC', '315 Buena Vista Way', 'Letizia Bonnyson', 'lbonnyson0@ovh.net');
insert into shops (name, address, owner, email) values ('AAA Pharmaceutical, Inc.', '6 Park Meadow Court', 'Jana Bresman', 'jbresman1@eepurl.com');
insert into shops (name, address, owner, email) values ('Bryant Ranch Prepack', '7 Service Plaza', 'Bebe Lorne', 'blorne2@yellowpages.com');
insert into shops (name, address, owner, email) values ('Nelco Laboratories, Inc.', '2 Shasta Trail', 'Gabrila Blaksley', 'gblaksley3@intel.com');
insert into shops (name, address, owner, email) values ('Unit Dose Services', '5137 Veith Parkway', 'Philippe Bletso', 'pbletso4@merriam-webster.com');
insert into shops (name, address, owner, email) values ('Upsher-Smith Laboratories, Inc.', '73061 Kings Alley', 'Helen-elizabeth Tamblingson', 'htamblingson5@patch.com');
insert into shops (name, address, owner, email) values ('Jubilant HollisterStier LLC', '166 Red Cloud Street', 'Doro Dingivan', 'ddingivan6@unicef.org');
insert into shops (name, address, owner, email) values ('Par Pharmaceutical Inc.', '039 Starling Court', 'Sumner Trembath', 'strembath7@japanpost.jp');
insert into shops (name, address, owner, email) values ('Preferred Pharmaceuticals, Inc', '7541 American Park', 'Brendis Chown', 'bchown8@reddit.com');
insert into shops (name, address, owner, email) values ('Asclemed USA, Inc.', '07840 2nd Crossing', 'Norine Cornejo', 'ncornejo9@elegantthemes.com');
insert into shops (name, address, owner, email) values ('Major Pharmeceuticals', '76 Esker Drive', 'Allen Natwick', 'anatwicka@hp.com');
insert into shops (name, address, owner, email) values ('Wal-Mart Stores Inc', '83287 Grim Street', 'Allys Grigoli', 'agrigolib@topsy.com');
insert into shops (name, address, owner, email) values ('Rebel Distributors Corp.', '22 Arizona Center', 'Selig Dummigan', 'sdummiganc@europa.eu');
insert into shops (name, address, owner, email) values ('Advance Pharmaceutical Inc.', '54 Grasskamp Center', 'Allissa Lilburn', 'alilburnd@guardian.co.uk');
insert into shops (name, address, owner, email) values ('H E B', '081 Columbus Avenue', 'Pasquale Dobrowlski', 'pdobrowlskie@walmart.com');
insert into shops (name, address, owner, email) values ('Preferred Pharmaceuticals, Inc', '456 Waubesa Hill', 'Mattheus Jellico', 'mjellicof@scribd.com');
insert into shops (name, address, owner, email) values ('Bausch & Lomb Incorporated', '96 Crowley Crossing', 'Whit Cayzer', 'wcayzerg@pcworld.com');
insert into shops (name, address, owner, email) values ('Aphena Pharma Solutions - Tennessee, LLC', '4754 Eastwood Lane', 'Ferdy Althrope', 'falthropeh@deliciousdays.com');
insert into shops (name, address, owner, email) values ('Rising Pharmaceuticals, Inc.', '73 Rowland Park', 'Bobbye Gurnee', 'bgurneei@istockphoto.com');
insert into shops (name, address, owner, email) values ('Gurwitch Products', '5804 Grasskamp Drive', 'Lorita Slavin', 'lslavinj@opera.com');
insert into shops (name, address, owner, email) values ('Novartis Pharmaceuticals Corporation', '6 Veith Junction', 'Leyla Goodsal', 'lgoodsalk@booking.com');
insert into shops (name, address, owner, email) values ('Franklin Pharmaceutical LLC', '6 3rd Crossing', 'Ricard Corona', 'rcoronal@time.com');
insert into shops (name, address, owner, email) values ('Guna spa', '7854 Norway Maple Circle', 'Livy Grennan', 'lgrennanm@istockphoto.com');
insert into shops (name, address, owner, email) values ('STAT RX USA LLC', '7857 Northwestern Alley', 'Bryan Cawston', 'bcawstonn@ucla.edu');
insert into shops (name, address, owner, email) values ('Option Labs', '66 Erie Way', 'Coralyn Coomes', 'ccoomeso@geocities.jp');
insert into shops (name, address, owner, email) values ('Qualitest Pharmaceuticals', '9649 Huxley Terrace', 'Mitchell Melliard', 'mmelliardp@xing.com');
insert into shops (name, address, owner, email) values ('ARMY AND AIR FORCE EXCHANGE SERVICE', '53 Saint Paul Terrace', 'Penn Kellough', 'pkelloughq@amazon.de');
insert into shops (name, address, owner, email) values ('Merck Sharp & Dohme Corp.', '944 Fair Oaks Court', 'Andrea Stonary', 'astonaryr@irs.gov');
insert into shops (name, address, owner, email) values ('Dharma Research, inc.', '07 Memorial Park', 'Annalee Thaim', 'athaims@digg.com');
insert into shops (name, address, owner, email) values ('AstraZeneca LP', '143 Packers Way', 'Audi Cornu', 'acornut@vinaora.com');
insert into shops (name, address, owner, email) values ('Teva Parenteral Medicines, Inc.', '064 Carberry Road', 'Valentine Binton', 'vbintonu@illinois.edu');
insert into shops (name, address, owner, email) values ('RITE AID CORPORATION', '6421 Stephen Terrace', 'Cyndi Martinec', 'cmartinecv@bloglovin.com');
insert into shops (name, address, owner, email) values ('AR Medicom Inc', '01056 Lotheville Parkway', 'Karyn Meaders', 'kmeadersw@telegraph.co.uk');
insert into shops (name, address, owner, email) values ('AMERICAN SALES COMPANY', '41816 Northland Lane', 'Burlie Ever', 'beverx@free.fr');
insert into shops (name, address, owner, email) values ('Mylan Institutional Inc.', '7 Bashford Pass', 'Tessi Crisall', 'tcrisally@aboutads.info');
insert into shops (name, address, owner, email) values ('American Sales Company', '847 Moulton Junction', 'Ramsey Arney', 'rarneyz@technorati.com');
insert into shops (name, address, owner, email) values ('McKesson', '5 Mayer Alley', 'Adrian McSperrin', 'amcsperrin10@ocn.ne.jp');
insert into shops (name, address, owner, email) values ('Guna spa', '2328 Harper Pass', 'Enrica Yukhnov', 'eyukhnov11@salon.com');
insert into shops (name, address, owner, email) values ('Aurobindo Pharma Limited', '62942 Mosinee Circle', 'Nobe Kellington', 'nkellington12@yahoo.com');
insert into shops (name, address, owner, email) values ('Rebel Distributors Corp', '501 Mifflin Way', 'Phillida Judge', 'pjudge13@geocities.com');
insert into shops (name, address, owner, email) values ('Western Family Foods Inc', '98 Bowman Court', 'Coleman Lamberteschi', 'clamberteschi14@ning.com');
insert into shops (name, address, owner, email) values ('General Injectables & Vaccines, Inc', '29 Northland Terrace', 'Clare Fothergill', 'cfothergill15@mediafire.com');
insert into shops (name, address, owner, email) values ('KAISER FOUNDATION HOSPITALS', '261 Golden Leaf Crossing', 'Vitia Lawland', 'vlawland16@globo.com');
insert into shops (name, address, owner, email) values ('Zep Inc.', '7753 Farwell Circle', 'Roselle Stanford', 'rstanford17@google.cn');
insert into shops (name, address, owner, email) values ('STAT Rx USA LLC', '04246 Anniversary Lane', 'Dalston Drillingcourt', 'ddrillingcourt18@cocolog-nifty.com');
insert into shops (name, address, owner, email) values ('SHISEIDO AMERICA INC.', '7588 Veith Plaza', 'Milena Chennells', 'mchennells19@usatoday.com');
insert into shops (name, address, owner, email) values ('Lifetech Resources, LLC', '00 Melody Center', 'Melisenda Follos', 'mfollos1a@posterous.com');
insert into shops (name, address, owner, email) values ('Teva Pharmaceuticals USA Inc', '824 Bayside Parkway', 'Hamish De Gowe', 'hde1b@paypal.com');
insert into shops (name, address, owner, email) values ('Teva Pharmaceuticals USA Inc', '275 Jackson Junction', 'Bert Koppe', 'bkoppe1c@cafepress.com');
insert into shops (name, address, owner, email) values ('RITE AID', '8 Cherokee Park', 'Kienan Welfare', 'kwelfare1d@webmd.com');
